project:
  type: website
  output-dir: docs

website:
  title: "dsfair_quarto"
  navbar:
    title: DSFAIR
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: R Basics
        menu:
          - text: First Steps
            href: rbasics/firststeps.qmd
          - text: The tidyverse
            href: rbasics/tidyverse.qmd
          - text: Correlation & Regression
            href: rbasics/correlation_regression.qmd
          - text: Bad data & Outliers
            href: rbasics/baddata.qmd
      - text: Simple Experiments
        menu:
          - text: 1w CRD (Mead 1993)
            href: exan/simple/crd_mead1993.qmd
          - text: 1w RCBD (Clewer & Scarisbrickt 2001)
            href: exan/simple/rcbd_clewerscarisbrick2001.qmd
          - text: 1w Latin Square (Bridges 1989)
            href: exan/simple/latsq_bridges1989.qmd
          - text: 2w RCBD (Gomez & Gomez 1984)
            href: exan/simple/rcbd_gomezgomez1984.qmd
          - text: 2w split-plot (Gomez & Gomez 1984)
            href: exan/simple/splitplot_gomezgomez1984.qmd
      - text: Complex Experiments
      - text: Summary Articles
        menu:
          - text: Useful things
            href: summaryarticles/usefulthings.qmd
          - text: ggplot2 tutorial
            href: summaryarticles/ggplot2intro.qmd
          - text: Compact Letter Display
            href: summaryarticles/compactletterdisplay.qmd
          - text: Designing Experiments
            href: summaryarticles/designingexperiments.qmd
          - text: Model Diagnostics
            href: summaryarticles/modeldiagnostics.qmd
          - text: Why SE equal
            href: summaryarticles/whyseequal.qmd
          - text: Workshop prep
            href: summaryarticles/workshopprep.qmd
    right:
      - text: Contact
        href: https://schmidtpaul.github.io/
      - icon: github
        href: https://github.com/SchmidtPaul
        aria-label: GitHub
  favicon: img/favicon-32x32.png
  image: img/hexagonDSFAIR.png
  site-url: https://schmidtpaul.github.io/dsfair_quarto/
  twitter-card:
    title: "Data Science for Agriculture in R"
    description: "a cookbook with statistical analyses of typical examples in life sciences with focus on experimental agriculture, biology, ecology and other related fields"
    image: img/hexagonDSFAIR.png
    creator: "@SchmidtPaul1989"
  # cookie-consent: true

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: true
    code-fold: false
    code-summary: "Click to show/hide code"
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-tools: true
    citations-hover: true
    footnotes-hover: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true

author:
  - name:
      given: Paul
      family: Schmidt
      literal: Paul Schmidt
    orcid: 0000-0003-1528-2082
    email: schmidtpaul1989@outlook.com
    affiliations:
      - name: Freelancer &
        url: https://schmidtpaul.github.io/
      - name: BioMath GmbH
        city: Hamburg
        country: Germany
        url: https://www.biomath.de/

editor: visual
abstract-title: "Content summary"
bibliography: references.bib
date: last-modified
published-title: "Last updated"

execute:
  warning: false
  message: false
  freeze: auto

fig-dpi: 300
fig-width: 5.5
fig-height: 3.5

body-header: | 
  <meta property="og:image" content="img/hexagonDSFAIR.png" />

filters: 
  - src/custom-callout-addref.lua
  - src/custom-callout-modass.lua
