project:
  type: website
  output-dir: docs

website:
  title: "dsfair_quarto"
  navbar:
    title: DSFAIR
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: R Basics
        menu:
          - text: First Steps
            href: ch/rbasics/firststeps.qmd
          - text: The tidyverse
            href: ch/rbasics/tidyverse.qmd
          - text: Correlation & Regression
            href: ch/rbasics/correlation_regression.qmd
          - text: Bad data & Outliers
            href: ch/rbasics/baddata.qmd
      - text: Simple Experiments
        menu:
          - text: 1w CRD (Mead 1993)
            href: ch/exan/simple/crd_mead1993.qmd
          - text: 1w RCBD (Clewer & Scarisbrickt 2001)
            href: ch/exan/simple/rcbd_clewerscarisbrick2001.qmd
          - text: 1w Latin Square (Bridges 1989)
            href: ch/exan/simple/latsq_bridges1989.qmd
          - text: 1w augmented (Petersen 1994)
            href: ch/exan/simple/augm_petersen1994.qmd
          - text: 1w alpha (John & Williams 1995)
            href: ch/exan/simple/alpha_johnwilliams1995.qmd
          - text: 1w rowcol (Kempton & Fox 1997)
            href: ch/exan/simple/rowcol_kemptonfox1997.qmd
          - text: 2w RCBD (Gomez & Gomez 1984)
            href: ch/exan/simple/rcbd_gomezgomez1984.qmd
          - text: 2w split-plot (Gomez & Gomez 1984)
            href: ch/exan/simple/splitplot_gomezgomez1984.qmd
      - text: Complex Experiments
      - text: Summary Articles
        menu:
          - text: ggplot2 tutorial
            href: ch/summaryarticles/ggplot2intro.qmd
          - text: Compact Letter Display
            href: ch/summaryarticles/compactletterdisplay.qmd
          - text: Designing Experiments
            href: ch/summaryarticles/designingexperiments.qmd
          - text: Model Diagnostics
            href: ch/summaryarticles/modeldiagnostics.qmd
          - text: Why SE equal
            href: ch/summaryarticles/whyseequal.qmd
          - text: Multiplicity Adjustment
            href: ch/summaryarticles/multiplicityadj.qmd
          - text: ANOVA Types
            href: ch/summaryarticles/anovatypes.qmd
          - text: Mixed Models
            href: ch/summaryarticles/mixedmodels.qmd
      - text: Misc
        menu:
          - text: Useful things
            href: ch/misc/usefulthings.qmd
          - text: Exercises
            href: ch/misc/exercises.qmd
          - text: Other Resources
            href: ch/misc/furtherresources.qmd
          - text: Workshop prep
            href: ch/misc/workshopprep.qmd
    right:
      - text: Contact
        href: https://schmidtpaul.github.io/
      - icon: github
        href: https://github.com/SchmidtPaul/dsfair_quarto
        aria-label: GitHub
  page-footer: 
    right:
      - text: '<p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>'
    border: true
    background: "#00923f"
  favicon: img/favicon-32x32.png
  image: img/hexagonDSFAIR.png
  site-url: https://schmidtpaul.github.io/dsfair_quarto/
  twitter-card:
    title: "Data Science for Agriculture in R"
    description: "a cookbook with statistical analyses of typical examples in life sciences with focus on experimental agriculture, biology, ecology and other related fields"
    image: img/hexagonDSFAIR.png
    creator: "@SchmidtPaul1989"
  # cookie-consent: true

format:
  html:
    anchor-sections: true
    css: include/styles.css
    code-fold: false
    code-summary: "Click to show/hide code"
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    theme: include/theme.scss
    toc: true
  pdf:
    colorlinks: true
    number-sections: true
    toc: true

# remove this once lightbox no longer needs an extension    
filters:
  - lightbox
lightbox:
  match: auto
  effect: fade
    
author:
  - name:
      given: Paul
      family: Schmidt
      literal: 'Paul Schmidt'
    # orcid: 0000-0003-1528-2082
    affiliations:
      - name: "BioMath GmbH"
        city: Hamburg
        country: Germany
        url: https://www.biomath.de/
      - name: "& Freelancer"
        url: https://schmidtpaul.github.io/

editor: visual
abstract-title: "Content summary"
bibliography: references.bib
date: last-modified
published-title: "Last updated"

execute:
  warning: false
  message: false
  freeze: auto

fig-dpi: 300
fig-width: 5.5
fig-height: 3.5

citation: true

body-header: | 
  <meta property="og:image" content="img/hexagonDSFAIR.png" />